### ISSUE TITLE
Investigate boolean satisfiability, see if this applies to this project

### ISSUE THREAD

**Issue by skagawa2** [AIDA-UIUC/uiuc-scheduler#1]
(I'll try not to intrude on this project much more)

This issue will contain the discussion regarding whether boolean satisfiability ([Wikipedia](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem)) will work for this problem (figuring out class prerequisites).

In general, it seems like satisfiability takes in an input of n booleans (x1, x2, ..., xn) and a "circuit" (series of ANDs and ORs) and sees if there is a combination of inputs that leads to a "true" output.

This issue can be closed once it is decided whether or not the problem applies.

**Comment by iyaja** [comment]
Regardless of whether or not an SAT solver is required for the actual visualizations, I think it's still probably a good idea to represent the "parse tree" from the description as the input to an SAT solver (i.e. what Wikipedia calls a boolean formula) for things like like visualization.

**Comment by JavierMNieto** [comment]
I think an SAT solver implemented on the frontend of the site will be a good way to quickly tell a user if they can take a course or not based on the courses they have already entered on the site. I think a graph database like [neo4j](https://neo4j.com/) would be great in connecting courses and easily represent the tree or just keeping the raw format of the boolean formula to pass to the frontend to solve with the user data.

**Comment by iyaja** [comment]
Just a quick follow-up on this. You don't actually need to properly *solve* a boolean formula for this project. You just need to check if a condition Is satisfied, not find out if the condition _can_ be satisfied. If there is any unsatisfiable formula in the course registry, that would be a big issue, because it would mean it's impossible to satisfy the prerequisites and take the class.

Instead, all you need to do is check if a given prerequisite formula/expression evaluates to TRUE. Example:

```
CS125 = TRUE
CS173 = FALSE
CS225 = CS173 AND CS125
CS 233 = CS225
CS 241 = CS 233 AND CS 225
CS 425 = CS225 AND CS 241
```

So if the user tries to add `CS425` you'd just have to recursively evaluate the prerequisites, which is easily handled on your graph via depth-first search. In this case, it's false, and you'd alert the user. No SAT solving required. 

Where the SAT solving libraries _will_ be useful, I think, is for actually representing and storing the prereq info as a boolean expression. They likely have fast and flexible data structures with helpful methods for that.

**Comment by iyaja** [comment]
@JavierMNieto can this be closed now? I think everything worth discussing about satisfiability has been discussed, and you guys have a solid plan with Neo4j, right?
